language: generic

sudo: required

services:
    - docker

script:
    - docker build -t jaswdr/gatekeeper .

after_success:
  - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
  - docker push jaswdr/gatekeeper;
