version: "3.5"

services:
  gate:
    build: .
    volumes:
      - ${PWD}/config/gate/nginx.conf:/usr/local/openresty/nginx/conf/nginx.conf:ro
      - ${PWD}/lua:/scripts:ro
    depends_on:
      - redis01
    links:
      - redis01
      - db
      - web01
      - web02
      - web03
      - api01
      - api02
      - api03
    ports:
      - "8081:80"
      - "9145:9145"

  redis01:
    image: redis

  db:
    image: postgres
    volumes:
      - ./database/dump.sql:/docker-entrypoint-initdb.d/dump.sql

  prometheus:
    image: prom/prometheus
    volumes:
      - ./config/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    links:
      - gate
      - exporter

  exporter:
    image: quay.io/prometheus/node-exporter

  grafana:
    image: grafana/grafana
    environment:
      - GF_DATABASE_URL=postgres://postgres:postgres@db:5432/grafana?currentSchema=grafana
      - GF_DATABASE_SSL_MODE=disable
      - GF_SESSION_PROVIDER=redis
      - GF_SESSION_PROVIDER_CONFIG=addr=redis01:6379,pool_size=100,db=grafana
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_SECURITY_LOGIN_REMEMBER_DAYS=7
      - GF_SECURITY_DISABLE_GRAVATAR=true
      - GF_USERS_ALLOW_SIGN_UP=false
      - GF_USERS_ALLOW_ORG_CREATE=false
    depends_on:
      - db
      - redis01
    links:
      - prometheus
      - db
      - redis01
    ports:
      - "3000:3000"

  broker:
    image: rabbitmq:management

  web01:
    image: nginx
    volumes:
      - ${PWD}/www/apps/web:/usr/share/nginx/html:ro

  web02:
    image: nginx
    volumes:
      - ${PWD}/www/apps/web:/usr/share/nginx/html:ro

  web03:
    image: nginx
    volumes:
      - ${PWD}/www/apps/web:/usr/share/nginx/html:ro

  api01:
    image: golang
    command: go run /src/github.com/jaswdr/template/main.go
    volumes:
      - ${PWD}/www/apps/api:/src/github.com/jaswdr/template:ro

  api02:
    image: golang
    command: go run /src/github.com/jaswdr/template/main.go
    volumes:
      - ${PWD}/www/apps/api:/src/github.com/jaswdr/template:ro

  api03:
    image: golang
    command: go run /src/github.com/jaswdr/template/main.go
    volumes:
      - ${PWD}/www/apps/api:/src/github.com/jaswdr/template:ro
