global:
  scrape_interval:     15s

scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'exporter'
    scrape_interval: 5s
    static_configs:
      - targets: ['exporter:9100']

  - job_name: 'gate'
    scrape_interval: 5s
    static_configs:
      - targets: ['gate:9145']
